---
- name: Load ansible modules
  hosts: all
  become: true
  connection: local
  pre_tasks:
    - ansible.builtin.import_tasks: pre_tasks/common.yml
    - ansible.builtin.import_tasks: pre_tasks/archlinux.yml
  tags:
    - always

# ---- Run roles
#  - hosts: all
#    become: true
#    connection: local
#    tags: base
#    roles:
#      - base
