---
- name: System-level setup for all hosts
  hosts: all
  connection: local
  roles:
    - system/package_manager

#  - name: User-level setup for all hosts
#    hosts: all
#    connection: local
#    roles:
#      - user/neovim
#      - user/librewolf
#      - user/zotero
