---
- name: Load ansible modules and install base packages
  hosts: all
  become: true
  connection: local
  pre_tasks:
    - name: Common modules
      ansible.builtin.import_tasks: "pre_tasks/common.yml"
    - name: Arch Linux modules
      ansible.builtin.import_tasks: "pre_tasks/Archlinux.yml"
      when: ansible_distribution == "Archlinux"
  roles:
    - neovim
