---
- name: System-level setup for all hosts
  hosts: all
  connection: local
  roles:
    - system/package_manager
  tasks:
    - debug:
        msg: "{{ ansible_env }}"
      tags:
        - test

- name: User-level setup for all hosts
  hosts: all
  connection: local
  roles:
    - user/neovim
    - user/firefox
    - user/zotero
    - user/megasync
    - user/cryptomator
