---
- name: Bootstrap necessary Ansible modules
  hosts: all
  connection: local
  tasks:
    - name: Common modules
      block:
        - name: Install community collection
          ansible.builtin.command: ansible-galaxy collection install community.general
          changed_when: false
      tags:
        - always

    - name: Arch-specific modules
      block:
        - name: Install Arch User Repository (AUR) collection
          ansible.builtin.command: ansible-galaxy collection install kewlfft.aur
          changed_when: false

        - name: Create `aur_builder` user
          ansible.builtin.user:
            name: aur_builder
            group: wheel
            create_home: true
          become: true

        - name: Allow `aur_builder` user to run `sudo pacman` without a password
          ansible.builtin.lineinfile:
            path: "/etc/sudoers.d/11-install-aur_builder"
            line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            mode: 0644
            create: true
            validate: "visudo -cf %s"
          become: true
      when: ansible_distribution == "Archlinux"
      tags:
        - always
