---
- name: Fetch user info
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: present
  register: user_info
  check_mode: true
  changed_when: false

- name: Copy neovim config for user `{{ user.name }}`
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ user_info.home }}/.config/nvim/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
