---
- name: Fetch user info
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: present
  register: user_info
  check_mode: true
  changed_when: false

- name: Create Firefox-related directories
  block:
    - ansible.builtin.file:
        path: "{{ user_info.home }}/{{ item }}"
        state: directory
        recurse: true
      become: true
      become_user: "{{ user.name }}"
      loop:
        - ".librewolf"
        - ".local/state/firefox/chrome"

    - ansible.builtin.file:
        path: "/usr/lib/librewolf/distribution"
        state: directory
        recurse: true
      become: true

- name: Symlink Firefox config for user `{{ user.name }}`
  block:
    - ansible.builtin.copy:
        src: "{{ role_path }}/files/{{ item.src }}"
        dest: "{{ user_info.home }}/{{ item.dest }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
      loop:
        - { src: "userChrome.css", dest: ".local/state/firefox/chrome/userChrome.css" }
        - { src: "firefox.desktop", dest: ".local/share/applications/firefox.desktop" }
        - { src: "user.js", dest: ".local/state/firefox/user.js" }

    - ansible.builtin.copy:
        src: "{{ role_path }}/files/policies.json"
        dest: "/opt/firefox-esr/distribution/policies.json"
