#!/bin/sh

sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"
userresources="$HOME/.config/Xresources"
usermodmap="$HOME/.config/Xmodmap"

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $userresources ] && xrdb -merge $userresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f $usermodmap ] && xmodmap $usermodmap

# Execute xinitrc.d scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3
