[pyprland]
plugins = [
    "scratchpads"
]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
animation = "fromTop"
unfocus = "hide"
lazy = true
margin = 125
size = "75% 75%"

[scratchpads.vifm]
command = "kitty --class fm-dropterm -e yazi"
class = "fm-dropterm"
animation = "fromTop"
unfocus = "hide"
lazy = true
margin = 125
size = "75% 75%"
